"""
YouTube Live Automation — AWS Lambda Handler
============================================
Automates weekly YouTube Live setup and reporting for SJCAC church channels
(Mandarin, English ES, English ES2, Spanish SS).
Triggered every Tuesday morning via EventBridge. No manual input is required
during normal weekly operation.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
WHAT IT DOES (two tasks per run)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  1. VIEWER REPORT
       Looks back at last Sunday's completed broadcasts, fetches the peak
       concurrent viewer count for each channel, and sends a formatted HTML
       summary email via Amazon SES.

  2. EVENT CREATOR
       Looks ahead to next Sunday, creates a scheduled YouTube Live broadcast
       on each channel with the correct title (in the channel's language),
       description (in the channel's language), start time, and thumbnail.
       Each broadcast is bound to that channel's existing persistent stream
       so the RTMP key in ProPresenter never changes. Each broadcast is also
       added to that channel's designated YouTube playlist automatically.
       Note: live chat and comments cannot be disabled via the YouTube API —
       disable them in YouTube Studio → Settings → Community → Defaults for
       each channel.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DATE LOGIC
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  The script runs on Tuesday and automatically calculates both target dates:

    Last Sunday  = the Sunday that just passed  → used for the viewer report
    Next Sunday  = the Sunday coming up          → used for event creation

  Example — script runs Tuesday May 6:
    Last Sunday  = May  4  ← fetch peak viewers from these streams
    Next Sunday  = May 11  ← create new live events for these streams

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CHANNEL CONFIG  (the only section you should ever need to edit)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Edit the CHANNELS dict and description constants below.
  Each channel entry controls everything about that service:
    - Which YouTube channel to post on
    - Which Google account to authenticate as
    - Which persistent stream to bind to (RTMP key stays the same forever)
    - What time the service starts
    - Which thumbnail to use
    - What title prefix to use (in the channel's own language)
    - Which YouTube playlist to add the broadcast to
    - What description text to use (in the channel's own language)

  All stream times are in America/Los_Angeles (PST/PDT — automatically
  adjusts for daylight saving).

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
THUMBNAILS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Thumbnails are stored as static files in S3 and reused every week.
  Upload them once — the script handles the rest automatically.

  Required S3 files (only 3):
    <EVENTS_S3_BUCKET>/thumbnails/mandarin.jpeg ← used by MS
    <EVENTS_S3_BUCKET>/thumbnails/english.jpg   ← used by ES & ES2
    <EVENTS_S3_BUCKET>/thumbnails/spanish.jpeg  ← used by SS

  Specs: JPG or PNG, 1280×720 px recommended, 2 MB max (YouTube limits).
  To swap a thumbnail, upload a new file to S3 with the same filename.
  No code changes or redeployment needed.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
ENVIRONMENT VARIABLES  (set once in the Lambda console → Configuration)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Google OAuth credentials (shared across all accounts):
    GOOGLE_CLIENT_ID        OAuth2 client ID from Google Cloud Console
    GOOGLE_CLIENT_SECRET    OAuth2 client secret from Google Cloud Console

  Per-account refresh tokens (generated by setup_credentials.py):
    MS_REFRESH_TOKEN        Authenticates Account 1 — Mandarin channel
    ES_REFRESH_TOKEN        Authenticates Account 2 — English ES channel
    ES2_REFRESH_TOKEN       Authenticates Account 3 — English ES2 channel
    SS_REFRESH_TOKEN        Authenticates Account 4 — Spanish SS channel (not yet configured)

  Persistent stream IDs (find in YouTube Studio → Go Live → Manage):
    MS_STREAM_ID            Stream ID for the Mandarin channel
    ES_STREAM_ID            Stream ID for the English ES channel
    ES2_STREAM_ID           Stream ID for the English ES2 channel
    SS_STREAM_ID            Stream ID for the Spanish SS channel

    ↑ These are the API resource IDs, not the human-readable stream key names.
      The stream ID stays the same forever. Binding to it means ProPresenter's
      RTMP key never needs to be updated.

  S3 / email:
    EVENTS_S3_BUCKET        Name of the S3 bucket holding thumbnails (e.g. your-bucket-name)
    SES_FROM_EMAIL          Sender address (must be verified in Amazon SES)
    SES_TO_EMAIL            Recipient address for the weekly report email
    SES_REGION              AWS region where SES is configured (us-west-2)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
EVENTBRIDGE SCHEDULE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Cron expression:  cron(0 17 ? * TUE *)
  Fires:            Every Tuesday at 9:00 AM PST / 10:00 AM PDT
  Input payload:    {} (empty — no input needed for normal operation)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
MANUAL / TEST INVOCATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Invoke the Lambda manually from the AWS console with one of these payloads:

    {}
        Run everything — viewer report + event creation for all channels.

    {"mode": "viewer_report"}
        Only fetch last Sunday's viewer counts and send the summary email.
        Does not create any YouTube events.

    {"mode": "create_events"}
        Only create next Sunday's YouTube Live events.
        Does not fetch viewer counts or send email.

    {"channel": "ms_channel"}
        Run both tasks for one channel only. No email is sent for single-channel
        runs. Valid values: "ms_channel", "es_channel", "es2_channel", "ss_channel".
        To add a new channel, add an entry to the CHANNELS dict.

    {"mode": "create_events", "channel": "ms_channel"}
        Create event for one channel only.

    {"dry_run": true}
        Full run — calculates everything and logs what it would do — but makes
        no writes to YouTube and sends no email. Safe to use for testing at any
        time without affecting live channels.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
HOW TO REBUILD AND DEPLOY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Run these commands from the project folder on your Mac:

    rm -rf build lambda_package.zip
    mkdir build
    pip install google-auth google-auth-oauthlib google-auth-httplib2 \\
      google-api-python-client \\
      --target build --platform mlinux_x86_64 --implementation cp \\
      --python-version 3.12 --only-binary=:all:
    cp handler.py build/handler.py
    cd build && zip -r ../lambda_package.zip . && cd ..

  Then go to Lambda → Upload From → .zip file and upload lambda_package.zip.

  IMPORTANT: Always use --platform mlinux_x86_64 when building on a Mac.
  Without it you get "invalid ELF header" errors in Lambda.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
KNOWN ISSUES AND DECISIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Live chat cannot be disabled via the YouTube API.
    The YouTube Data API v3 LiveBroadcastContentDetails schema has no field
    for enabling or disabling live chat. Must be turned off manually per
    broadcast: YouTube Studio → Content → Live → Edit → Customization → Live chat off.
    Comments are handled via YouTube Studio → Settings → Community → Defaults (Comments: Off).

  ES2 channel has embed disabled.
    The Willow Glen YouTube account has embedding disabled at the account level.
    enable_embed: False is set to prevent API errors.

  SES is in us-west-2 not us-east-1.
    SES_REGION must be us-west-2 to match where emails were verified.

  OAuth tokens must use both youtube and yt-analytics.readonly scopes.
    Tokens generated with only youtube scope cause invalid_scope errors when
    the Analytics API is called. Always run get_refresh_token.py with both
    scopes defined. When authorizing, the consent screen must show both
    "Manage your YouTube account" AND "View YouTube Analytics reports".
"""

import datetime
import json
import logging
import os
import urllib.error
import urllib.request
import zoneinfo
from typing import Any

import boto3
from botocore.exceptions import ClientError
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

logger = logging.getLogger()
logger.setLevel(logging.INFO)

s3 = boto3.client("s3")
PST = zoneinfo.ZoneInfo("America/Los_Angeles")


# ══════════════════════════════════════════════════════════════════════════════
# DESCRIPTIONS — one per language
# ══════════════════════════════════════════════════════════════════════════════
# Each channel uses its own description in the correct language.
# Update the text here to change what appears in the YouTube video description.
# Plain text and URLs only — YouTube does not render markdown.

DESC_MANDARIN = (
    "如果您是第一次參加我們的崇拜，邀請您上我們教會的網頁查詢：https://www.sjcac.org"
    "\n\n---\n\n"
    "支持山河市華人宣道會事工，可用以下方法:\n"
    "網上奉獻: https://www.sjcac.org/tw/giving\n"
    "短訊奉獻: (424) 543-2311\n"
    "支票"
    '支票抬頭請寫 "San Jose Christian Alliance Church"，在備註行上註明奉獻項目。\n'
    "郵寄至 2360 McLaughlin Ave., San Jose, CA 95122"
)

DESC_ENGLISH = (
    "Welcome and thank you for joining us for our online worship service today! "
    "We would love to connect with you and get to know you better. "
    "If this is your first time worshiping with us, please fill out our online "
    "Connection Card, https://forms.gle/LGZ2mhzJdqEt4MRL6. "
    "\n\n---\n\n"
    "Want to know more about us? Email: info@sjcac.org "
    "Website: https://www.sjcac.org "
    "\n\n---\n\n"
    "Online donation: https://www.sjcac.org/giving "
    "Text donation: (424) 543-2311"
)

DESC_SPANISH = (
    "¡Bienvenidos y gracias por unirse hoy a nuestro servicio de adoración en línea! "
    "Nos encantaría conectarnos con usted y conocerle mejor. "
    "Si esta es su primera vez adorando con nosotros, por favor complete nuestra "
    "Tarjeta de Conexión en línea: https://forms.gle/LGZ2mhzJdqEt4MRL6. "
    "\n\n---\n\n"
    "¿Quiere saber más sobre nosotros? Correo electrónico: info@sjcac.org "
    "Sitio web: https://www.sjcac.org "
    "\n\n---\n\n"
    "Donaciones en línea: https://www.sjcac.org/giving "
    "Donaciones por mensaje de texto: (424) 543-2311"
)


# ══════════════════════════════════════════════════════════════════════════════
# CHANNEL CONFIG  —  edit this section to configure your channels
# ══════════════════════════════════════════════════════════════════════════════
#
# Each entry in CHANNELS controls one YouTube channel. Fields:
#
#   label               Human-readable name shown in logs and the weekly email.
#
#   title_prefix        The start of the broadcast title in the channel's language.
#                       The date is appended automatically.
#                       e.g. "普通話主日崇拜" → "普通話主日崇拜 – May 11, 2026"
#
#   description         The video description posted on every broadcast.
#                       Use the DESC_ constants defined above — one per language.
#
#   channel_id          The YouTube channel's unique ID (format: UCxxxxxxxxxxxxxxxxxxxx).
#                       Find it: YouTube Studio → Settings → Channel → Advanced Settings
#
#   stream_id_env       Name of the Lambda env var holding the persistent stream ID.
#                       Find the stream ID: YouTube Studio → Go Live → Manage.
#
#   refresh_token_env   Name of the Lambda env var holding the OAuth2 refresh token
#                       for the Google account that owns this channel.
#
#   stream_hour         Hour the service starts, 24-hour format, PST/PDT.
#
#   stream_minute       Minute the service starts.
#
#   privacy             "public" | "unlisted" | "private"
#
#   thumbnail_s3_key    Path in the S3 bucket to the thumbnail image for this channel.
#
#   playlist_id         (optional) YouTube playlist ID to add each broadcast to.
#                       Find it: YouTube Studio → Content → Playlists → click playlist
#                       → copy the PLxxxxxxxxxxxxxxxxxxxx from the URL.
#                       Leave blank ("") or omit to skip playlist assignment.
#
#   enable_embed        (optional, default True) Set to False for ES2 which has
#                       embedding disabled at the account level.

CHANNELS = {
    # ── Account 1 — Mandarin ──────────────────────────────────────────────────
    "ms_channel": {
        "label": "Mandarin",
        "title_prefix": "普通話主日崇拜",  # Title in Mandarin
        "description": DESC_MANDARIN,
        "channel_id": "UCpqWm2IWYLVYpInigPeX8Jw",
        "stream_id_env": "MS_STREAM_ID",
        "refresh_token_env": "MS_REFRESH_TOKEN",
        "stream_hour": 11,
        "stream_minute": 15,
        "privacy": "public",
        "thumbnail_s3_key": "thumbnails/mandarin.jpeg",
        "playlist_id": "PLuYWWkynBp33gmo4s804-bXpFj9-zYlCk",  # ← paste Mandarin playlist ID here
    },
    # ── Account 2 — English San Jose ──────────────────────────────────────────
    "es_channel": {
        "label": "English",
        "title_prefix": "English Sunday Service",
        "description": DESC_ENGLISH,
        "channel_id": "UCF1AWC7eWqONw7hGXcafU1A",
        "stream_id_env": "ES_STREAM_ID",
        "refresh_token_env": "ES_REFRESH_TOKEN",
        "stream_hour": 11,
        "stream_minute": 15,
        "privacy": "public",
        "thumbnail_s3_key": "thumbnails/english.jpg",
        "playlist_id": "PL1bVn1m-OhCbryXNCeGvTZJTAjqLRFhg8",  # ← paste English ES playlist ID here
    },
    # ── Account 3 — English Willow Glen ───────────────────────────────────────
    "es2_channel": {
        "label": "English (Willow Glen)",
        "title_prefix": "English Sunday Service",
        "description": DESC_ENGLISH,
        "channel_id": "UCc8oOM8m6Ko_FLsL-9ZsyKw",
        "stream_id_env": "ES2_STREAM_ID",
        "refresh_token_env": "ES2_REFRESH_TOKEN",
        "stream_hour": 9,
        "stream_minute": 30,
        "privacy": "public",
        "thumbnail_s3_key": "thumbnails/english.jpg",
        "enable_embed": False,  # Willow Glen account has embed disabled
        "playlist_id": "PLKkPCwC8wKDWgJegP_g_gdv6XCHiVobfN",  # ← paste English ES2 playlist ID here
    },
    # ── Account 4 — Spanish ────────────────────────────────────────────────────
    "ss_channel": {
        "label": "Spanish",
        "title_prefix": "Servicio Dominical",  # Title in Spanish
        "description": DESC_SPANISH,
        "channel_id": "UCChD2XmFqDSpezg-tdmMhnw",
        "stream_id_env": "SS_STREAM_ID",
        "refresh_token_env": "SS_REFRESH_TOKEN",
        "stream_hour": 19,
        "stream_minute": 00,
        "privacy": "public",
        "thumbnail_s3_key": "thumbnails/spanish.jpeg",
        "playlist_id": "PL4Z3nCSWdMCChB0DRfVawelvLLDaojvpM",
        "enable_embed": False,  # Spanish account has embed disabled at account level
    },
}


# ══════════════════════════════════════════════════════════════════════════════
# DATE HELPERS
# ══════════════════════════════════════════════════════════════════════════════
# Utility functions for calculating the two target Sundays and formatting dates.
# No configuration needed here.


def get_last_sunday() -> datetime.date:
    """Return the date of the most recent Sunday (always in the past)."""
    today = datetime.date.today()
    days_since_sunday = (today.weekday() + 1) % 7
    return today - datetime.timedelta(
        days=days_since_sunday if days_since_sunday > 0 else 7
    )


def get_next_sunday() -> datetime.date:
    """Return the date of the coming Sunday (always in the future)."""
    today = datetime.date.today()
    days_until_sunday = (6 - today.weekday()) % 7
    return today + datetime.timedelta(
        days=days_until_sunday if days_until_sunday > 0 else 7
    )


def make_stream_datetime(
    date: datetime.date, hour: int, minute: int
) -> datetime.datetime:
    """Build a timezone-aware PST/PDT datetime for a given date and time."""
    return datetime.datetime(date.year, date.month, date.day, hour, minute, tzinfo=PST)


def format_date(date: datetime.date) -> str:
    """Format a date as 'May 11, 2026'."""
    return date.strftime("%B %-d, %Y")


# ══════════════════════════════════════════════════════════════════════════════
# AUTH
# ══════════════════════════════════════════════════════════════════════════════
# Handles Google OAuth2 authentication. Each channel's refresh token is stored
# in a Lambda environment variable and exchanged for a short-lived access token
# at runtime. The access token is never stored — it exists only for the duration
# of the Lambda invocation.
#
# IMPORTANT: Refresh tokens must be generated with BOTH scopes:
#   - https://www.googleapis.com/auth/youtube           (create/manage events)
#   - https://www.googleapis.com/auth/yt-analytics.readonly  (viewer counts)
# The consent screen must show "Manage your YouTube account" AND
# "View YouTube Analytics reports" when you run get_refresh_token.py.


def get_youtube_client(refresh_token: str) -> tuple:
    """
    Build authenticated YouTube Data AND YouTube Analytics API clients.
    Returns (youtube, youtube_analytics) tuple.

    The Analytics client is used as a reliable fallback for viewer counts
    on streams that ended days ago — the Videos API clears concurrentViewers
    within a few hours of a stream ending, but the Analytics API stores
    peakConcurrentViewers permanently.

    Called once per channel per invocation. Uses GOOGLE_CLIENT_ID and
    GOOGLE_CLIENT_SECRET from Lambda environment variables.
    """
    creds = Credentials(
        token=None,
        refresh_token=refresh_token,
        client_id=os.environ["GOOGLE_CLIENT_ID"],
        client_secret=os.environ["GOOGLE_CLIENT_SECRET"],
        token_uri="https://oauth2.googleapis.com/token",
        scopes=[
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/yt-analytics.readonly",
        ],
    )
    creds.refresh(Request())
    youtube = build("youtube", "v3", credentials=creds, cache_discovery=False)
    youtube_analytics = build(
        "youtubeAnalytics", "v2", credentials=creds, cache_discovery=False
    )
    return youtube, youtube_analytics


def get_refresh_token(channel: dict) -> str | None:
    """
    Read a channel's OAuth2 refresh token from Lambda environment variables.

    Returns None and logs an error if the variable is missing, which causes
    the calling function to skip that channel gracefully rather than crash.
    """
    token = os.environ.get(channel["refresh_token_env"])
    if not token:
        logger.error("Missing env var: %s", channel["refresh_token_env"])
    return token


# ══════════════════════════════════════════════════════════════════════════════
# THUMBNAIL HELPER
# ══════════════════════════════════════════════════════════════════════════════
# Downloads a thumbnail image from S3 and uploads it to a YouTube broadcast.
# Thumbnails are stored in S3 once and reused automatically every week —
# no manual uploads or file management required after initial setup.


def upload_thumbnail(youtube, broadcast_id: str, bucket: str, s3_key: str) -> bool:
    """
    Download a thumbnail image from S3 and set it on a YouTube broadcast.

    The image is read into memory and streamed directly to the YouTube
    Thumbnails API — it is never written to disk.

    Returns True on success, False on any failure. Failures are non-fatal:
    the broadcast is still valid and will go live even without a thumbnail.

    YouTube thumbnail requirements:
        Format:      JPG or PNG
        Max size:    2 MB
        Recommended: 1280x720 px (16:9 aspect ratio)
    """
    try:
        obj = s3.get_object(Bucket=bucket, Key=s3_key)
        image_data = obj["Body"].read()
        content_type = obj.get("ContentType", "image/jpeg")

        logger.info(
            "Uploading thumbnail from s3://%s/%s (%d bytes)",
            bucket,
            s3_key,
            len(image_data),
        )

        from googleapiclient.http import MediaInMemoryUpload

        media = MediaInMemoryUpload(image_data, mimetype=content_type, resumable=False)

        youtube.thumbnails().set(
            videoId=broadcast_id,
            media_body=media,
        ).execute()

        logger.info("Thumbnail uploaded for broadcast: %s", broadcast_id)
        return True

    except s3.exceptions.NoSuchKey:
        logger.error("Thumbnail not found in S3: s3://%s/%s", bucket, s3_key)
        logger.error("Please upload your thumbnail to S3 before running.")
        return False
    except HttpError as e:
        logger.error("YouTube thumbnail upload failed for %s: %s", broadcast_id, e)
        return False
    except Exception as e:
        logger.error("Unexpected thumbnail error for %s: %s", broadcast_id, e)
        return False


# ══════════════════════════════════════════════════════════════════════════════
# PLAYLIST HELPER
# ══════════════════════════════════════════════════════════════════════════════
# Adds a newly created broadcast to a YouTube playlist.
# Playlist IDs are configured per channel in the CHANNELS dict above.
# This step is non-fatal — if it fails, the broadcast is still valid.


def add_to_playlist(youtube, playlist_id: str, broadcast_id: str) -> bool:
    """
    Add a broadcast video to a YouTube playlist.

    Uses the playlistItems().insert() API call. The playlist must belong to
    the same Google account that owns the broadcast.

    Returns True on success, False on failure. Failures are non-fatal —
    the broadcast goes live normally even if playlist insertion fails.
    """
    try:
        youtube.playlistItems().insert(
            part="snippet",
            body={
                "snippet": {
                    "playlistId": playlist_id,
                    "resourceId": {
                        "kind": "youtube#video",
                        "videoId": broadcast_id,
                    },
                }
            },
        ).execute()
        logger.info("Added broadcast %s to playlist %s", broadcast_id, playlist_id)
        return True
    except HttpError as e:
        logger.warning(
            "Could not add broadcast %s to playlist %s: %s",
            broadcast_id,
            playlist_id,
            e,
        )
        return False


# ══════════════════════════════════════════════════════════════════════════════
# VIEWER REPORT — looks back at last Sunday's completed broadcasts
# ══════════════════════════════════════════════════════════════════════════════
# Fetches the peak concurrent viewer count for each channel's most recent
# completed broadcast. Results are collected across all channels and included
# in the weekly summary email.


def get_last_completed_broadcast(
    youtube, channel_id: str, last_sunday: datetime.date
) -> dict | None:
    """
    Find the most recently completed broadcast for a channel.

    Prefers a broadcast scheduled on last Sunday's date. Falls back to the
    most recent completed broadcast overall if none is found for that exact
    date — this handles edge cases like holiday schedule changes.

    Returns the full broadcast resource dict from the YouTube API, or None
    if no completed broadcasts exist for the channel.
    """
    try:
        response = (
            youtube.liveBroadcasts()
            .list(
                part="snippet,status,statistics",
                broadcastStatus="completed",
                broadcastType="all",
                maxResults=10,
            )
            .execute()
        )

        broadcasts = [
            b
            for b in response.get("items", [])
            if b["snippet"].get("channelId") == channel_id
        ]

        if not broadcasts:
            logger.warning("No completed broadcasts found for channel: %s", channel_id)
            return None

        sunday_str = last_sunday.isoformat()
        sunday_broadcasts = [
            b
            for b in broadcasts
            if b["snippet"].get("scheduledStartTime", "").startswith(sunday_str)
        ]

        pool = sunday_broadcasts if sunday_broadcasts else broadcasts
        pool.sort(
            key=lambda b: b["snippet"].get("scheduledStartTime", ""), reverse=True
        )
        return pool[0]

    except HttpError as e:
        logger.error("YouTube API error fetching broadcasts for %s: %s", channel_id, e)
        return None


def get_max_concurrent_viewers(
    youtube, youtube_analytics, broadcast_id: str, channel_id: str
) -> int | None:
    """
    Fetch the peak concurrent viewer count for a completed broadcast.

    Strategy:
      1. First tries liveStreamingDetails.concurrentViewers from the Videos API
         — fast but only available briefly (a few hours) after the stream ends.
      2. Falls back to the YouTube Analytics API peakConcurrentViewers metric,
         which stores data permanently and works days or weeks after the stream.
         This is the method that runs on Tuesday for Sunday streams.

    Returns the peak viewer count as an int, or None if unavailable from either source.
    """
    # ── Attempt 1: Videos API (works right after stream ends) ─────────────────
    try:
        response = (
            youtube.videos()
            .list(
                part="liveStreamingDetails,snippet",
                id=broadcast_id,
            )
            .execute()
        )
        items = response.get("items", [])
        if items:
            viewers = items[0].get("liveStreamingDetails", {}).get("concurrentViewers")
            if viewers is not None:
                logger.info("Viewer count from Videos API: %s", viewers)
                return int(viewers)
    except HttpError as e:
        logger.warning("Videos API failed for %s: %s", broadcast_id, e)

    # ── Attempt 2: YouTube Analytics API (reliable for streams 3+ days old) ───
    if youtube_analytics is None:
        logger.warning(
            "Analytics client not available — cannot fall back for %s", broadcast_id
        )
        return None

    try:
        # Get actual start/end times from the video resource
        video_resp = (
            youtube.videos()
            .list(
                part="snippet,liveStreamingDetails",
                id=broadcast_id,
            )
            .execute()
        )

        video_items = video_resp.get("items", [])
        if not video_items:
            return None

        snippet = video_items[0].get("snippet", {})
        live_details = video_items[0].get("liveStreamingDetails", {})

        start_time = live_details.get("actualStartTime") or snippet.get(
            "publishedAt", ""
        )
        end_time = live_details.get("actualEndTime")

        if not start_time:
            return None

        start_date = start_time[:10]
        end_date = end_time[:10] if end_time else start_date

        # Query Analytics for peak concurrent viewers.
        # NOTE: dimensions="video" is intentionally omitted — the Analytics API
        # does not support peakConcurrentViewers with a video dimension filter.
        # Without dimensions, rows[0] = [peak_viewers] (a single value).
        analytics_resp = (
            youtube_analytics.reports()
            .query(
                ids=f"channel=={channel_id}",
                startDate=start_date,
                endDate=end_date,
                metrics="peakConcurrentViewers",
                filters=f"video=={broadcast_id}",
            )
            .execute()
        )

        rows = analytics_resp.get("rows", [])
        if rows:
            peak = rows[0][0]  # Single value — no dimension column
            logger.info("Peak viewers from Analytics API: %s", peak)
            return int(peak)

        logger.warning("Analytics API returned no rows for broadcast %s", broadcast_id)
        return None

    except HttpError as e:
        logger.error("Analytics API error for %s: %s", broadcast_id, e)
        return None


def fetch_viewer_stats(
    channel_key: str, channel: dict, last_sunday: datetime.date
) -> dict:
    """
    Fetch last Sunday's peak concurrent viewer count for one channel.

    Authenticates, finds the most recent completed broadcast, and returns
    a result dict with status "success" and the viewer count, or status
    "error" with a descriptive message if any step fails.

    Errors are non-fatal — a failure on one channel does not stop the
    other channels from being processed.
    """
    label = channel["label"]
    channel_id = channel["channel_id"]

    if channel_id.startswith("YOUR_"):
        return {
            "status": "error",
            "channel": channel_key,
            "label": label,
            "error": "Channel ID not configured",
        }

    refresh_token = get_refresh_token(channel)
    if not refresh_token:
        return {
            "status": "error",
            "channel": channel_key,
            "label": label,
            "error": f"Missing env var: {channel['refresh_token_env']}",
        }

    try:
        youtube, youtube_analytics = get_youtube_client(refresh_token)
    except Exception as e:
        return {
            "status": "error",
            "channel": channel_key,
            "label": label,
            "error": f"Auth failed: {e}",
        }

    broadcast = get_last_completed_broadcast(youtube, channel_id, last_sunday)
    if not broadcast:
        return {
            "status": "error",
            "channel": channel_key,
            "label": label,
            "error": "No completed broadcast found for last Sunday",
        }

    broadcast_id = broadcast["id"]
    broadcast_title = broadcast["snippet"].get("title", "Unknown")
    scheduled_start = broadcast["snippet"].get("scheduledStartTime", "")
    stream_date = scheduled_start[:10] if scheduled_start else "Unknown"

    max_viewers = get_max_concurrent_viewers(
        youtube, youtube_analytics, broadcast_id, channel_id
    )
    if max_viewers is None:
        return {
            "status": "error",
            "channel": channel_key,
            "label": label,
            "broadcast_title": broadcast_title,
            "error": "Viewer count not yet available",
        }

    logger.info(
        "[%s] Max viewers: %s for '%s'", channel_key, max_viewers, broadcast_title
    )
    return {
        "status": "success",
        "channel": channel_key,
        "label": label,
        "broadcast_id": broadcast_id,
        "broadcast_title": broadcast_title,
        "stream_date": stream_date,
        "watch_url": f"https://www.youtube.com/watch?v={broadcast_id}",
        "max_concurrent_viewers": max_viewers,
    }


# ══════════════════════════════════════════════════════════════════════════════
# EVENT CREATOR — looks ahead to next Sunday's upcoming broadcasts
# ══════════════════════════════════════════════════════════════════════════════
# Creates a scheduled YouTube Live broadcast for each channel and binds it to
# that channel's existing persistent stream. Because the stream is persistent,
# the RTMP ingest key in ProPresenter never needs to change — new broadcasts
# just appear each week bound to the same key.
#
# Each broadcast is also added to the channel's playlist automatically.
# Note: live chat and comments must be disabled in YouTube Studio → Settings →
# Community → Defaults — the YouTube API does not support disabling them.


def create_live_event(
    youtube,
    channel_id: str,
    stream_id: str,
    title: str,
    start_time: datetime.datetime,
    privacy: str,
    description: str,
    enable_embed: bool = True,
) -> dict:
    """
    Create a scheduled YouTube Live broadcast and bind it to a persistent stream.

    This function performs two API calls in sequence:

      1. liveBroadcasts().insert()
             Creates the broadcast with title, description, start time, and privacy.

      2. liveBroadcasts().bind()
             Binds the broadcast to the channel's existing persistent stream
             (identified by stream_id). This keeps the RTMP key in ProPresenter
             stable week to week. No new stream is ever created by this function.

    Note: comment disabling is not handled here — YouTube's API does not reliably
    apply commentStatus to live broadcasts. Set the default in YouTube Studio →
    Settings → Community → Defaults for each channel instead.

    Returns a dict with status "created" and the broadcast details on success.
    """

    # 1. Create broadcast — chat and chat replay disabled at insert time
    broadcast = (
        youtube.liveBroadcasts()
        .insert(
            part="snippet,status,contentDetails",
            body={
                "snippet": {
                    "title": title,
                    "description": description,
                    "scheduledStartTime": start_time.isoformat(),
                    "channelId": channel_id,
                },
                "status": {
                    "privacyStatus": privacy,
                    "selfDeclaredMadeForKids": False,
                },
                "contentDetails": {
                    "enableAutoStart": False,
                    "enableAutoStop": False,
                    "enableDvr": True,
                    "enableEmbed": enable_embed,
                    "recordFromStart": True,
                    "monitorStream": {
                        "enableMonitorStream": True,
                        "broadcastStreamDelayMs": 0,
                    },
                },
            },
        )
        .execute()
    )

    broadcast_id = broadcast["id"]

    # 2. Bind broadcast to the existing persistent stream.
    #    No liveStreams().insert() — the RTMP key never changes.
    youtube.liveBroadcasts().bind(
        part="id,contentDetails",
        id=broadcast_id,
        streamId=stream_id,
    ).execute()
    logger.info(
        "[%s] Bound broadcast %s to persistent stream %s",
        channel_id,
        broadcast_id,
        stream_id,
    )

    logger.info("[%s] Created broadcast: %s → %s", channel_id, title, broadcast_id)
    return {
        "status": "created",
        "broadcast_id": broadcast_id,
        "stream_id": stream_id,
        "watch_url": f"https://www.youtube.com/watch?v={broadcast_id}",
        "title": title,
        "start_time": start_time.isoformat(),
    }


def schedule_next_event(
    channel_key: str, channel: dict, next_sunday: datetime.date, dry_run: bool = False
) -> dict:
    """
    Orchestrate the full event creation flow for one channel.

    Steps:
      1. Validate the channel ID and resolve credentials from env vars.
      2. Build the broadcast title from title_prefix + date
         e.g. "普通話主日崇拜 – May 11, 2026"
      3. Call create_live_event() to create the broadcast and bind the stream.
      4. Upload the channel's thumbnail from S3.
      5. Add the broadcast to the channel's playlist (if configured).

    Returns a result dict with status "created" on success, "dry_run" if
    dry_run=True (no YouTube writes made), or "error" with a message if
    any step fails. Errors on one channel do not affect other channels.
    """
    label = channel["label"]
    channel_id = channel["channel_id"]
    bucket = os.environ.get("EVENTS_S3_BUCKET", "")

    if channel_id.startswith("YOUR_"):
        return {
            "status": "error",
            "channel": channel_key,
            "label": label,
            "error": "Channel ID not configured — replace placeholder in CHANNELS config",
        }

    refresh_token = get_refresh_token(channel)
    if not refresh_token:
        return {
            "status": "error",
            "channel": channel_key,
            "label": label,
            "error": f"Missing env var: {channel['refresh_token_env']}",
        }

    stream_id = os.environ.get(channel["stream_id_env"])
    if not stream_id:
        return {
            "status": "error",
            "channel": channel_key,
            "label": label,
            "error": f"Missing env var: {channel['stream_id_env']}",
        }

    # Build title from the channel's language-specific prefix + formatted date
    # e.g. "普通話主日崇拜 – May 11, 2026" or "English Sunday Service – May 11, 2026"
    date_str = format_date(next_sunday)
    title = f"{channel['title_prefix']} – {date_str}"

    start_time = make_stream_datetime(
        next_sunday, channel["stream_hour"], channel["stream_minute"]
    )

    logger.info(
        "[%s] Scheduling: '%s' at %s",
        channel_key,
        title,
        start_time.strftime("%I:%M %p PST"),
    )

    if dry_run:
        return {
            "status": "dry_run",
            "channel": channel_key,
            "label": label,
            "title": title,
            "start_time": start_time.isoformat(),
            "thumbnail_s3_key": channel["thumbnail_s3_key"],
            "note": "Dry run — no event created on YouTube, no thumbnail uploaded",
        }

    try:
        youtube, _ = get_youtube_client(refresh_token)
    except Exception as e:
        return {
            "status": "error",
            "channel": channel_key,
            "label": label,
            "error": f"Auth failed: {e}",
        }

    try:
        result = create_live_event(
            youtube=youtube,
            channel_id=channel_id,
            stream_id=stream_id,
            title=title,
            start_time=start_time,
            privacy=channel["privacy"],
            description=channel["description"],
            enable_embed=channel.get("enable_embed", True),
        )
        result.update({"channel": channel_key, "label": label})

        # Upload thumbnail from S3
        thumbnail_ok = False
        if bucket and channel.get("thumbnail_s3_key"):
            thumbnail_ok = upload_thumbnail(
                youtube=youtube,
                broadcast_id=result["broadcast_id"],
                bucket=bucket,
                s3_key=channel["thumbnail_s3_key"],
            )
        else:
            logger.warning(
                "[%s] No thumbnail configured or EVENTS_S3_BUCKET not set", channel_key
            )

        result["thumbnail_uploaded"] = thumbnail_ok

        # Add to playlist if one is configured for this channel
        playlist_id = channel.get("playlist_id", "")
        if playlist_id:
            playlist_ok = add_to_playlist(
                youtube=youtube,
                playlist_id=playlist_id,
                broadcast_id=result["broadcast_id"],
            )
            result["playlist_added"] = playlist_ok
        else:
            result["playlist_added"] = False

        return result

    except HttpError as e:
        logger.error("[%s] YouTube API error: %s", channel_key, e)
        return {
            "status": "error",
            "channel": channel_key,
            "label": label,
            "error": str(e),
        }
    except Exception as e:
        logger.error("[%s] Unexpected error: %s", channel_key, e)
        return {
            "status": "error",
            "channel": channel_key,
            "label": label,
            "error": str(e),
        }


# ══════════════════════════════════════════════════════════════════════════════
# EMAIL REPORT — weekly summary via Amazon SES
# ══════════════════════════════════════════════════════════════════════════════
# Builds and sends an HTML email summarising both tasks for the week:
#   - Last Sunday's peak viewer counts for all channels
#   - Next Sunday's newly created events with title, time, and thumbnail status
# Sent to SES_TO_EMAIL from SES_FROM_EMAIL (both set in Lambda env vars).
# Email is skipped automatically for single-channel runs and dry runs.


def build_email(
    viewer_results: list[dict],
    event_results: list[dict],
    last_sunday: datetime.date,
    next_sunday: datetime.date,
) -> tuple[str, str]:
    """
    Build the weekly summary email from the collected results of both tasks.

    Returns a (subject, html_body) tuple ready to pass to send_email().
    The subject line includes today's date and an overall pass/fail indicator.
    The HTML body contains two tables: one for viewer counts, one for the
    newly created events. Rows show a checkmark or error icon per channel.
    """
    all_ok = all(
        r["status"] in ("success", "dry_run", "created")
        for r in viewer_results + event_results
    )
    status_line = (
        "All channels completed successfully" if all_ok else "Some channels had issues"
    )
    run_date = datetime.date.today().strftime("%B %-d, %Y")
    subject = f"YouTube Weekly Report – {run_date} | {status_line}"

    def status_icon(s):
        return (
            "✅" if s in ("success", "created") else ("🔄" if s == "dry_run" else "❌")
        )

    # ── Viewer rows ──
    viewer_rows = ""
    for r in viewer_results:
        icon = status_icon(r["status"])
        if r["status"] == "success":
            viewers = f"{r['max_concurrent_viewers']:,}"
            url = r["watch_url"]
            title = r["broadcast_title"]
            viewer_rows += f"""
            <tr>
                <td style="padding:10px;border-bottom:1px solid #eee;font-weight:bold">{r['label']}</td>
                <td style="padding:10px;border-bottom:1px solid #eee">
                    <a href="{url}" style="color:#1a73e8;text-decoration:none">{title}</a>
                </td>
                <td style="padding:10px;border-bottom:1px solid #eee;text-align:center;font-size:1.2em;font-weight:bold;color:#1a73e8">{viewers}</td>
                <td style="padding:10px;border-bottom:1px solid #eee;text-align:center">{icon}</td>
            </tr>"""
        else:
            viewer_rows += f"""
            <tr>
                <td style="padding:10px;border-bottom:1px solid #eee;font-weight:bold">{r['label']}</td>
                <td style="padding:10px;border-bottom:1px solid #eee;color:#888" colspan="2">{r.get('error','Unknown error')}</td>
                <td style="padding:10px;border-bottom:1px solid #eee;text-align:center">{icon}</td>
            </tr>"""

    # ── Event rows ──
    event_rows = ""
    for r in event_results:
        icon = status_icon(r["status"])
        if r["status"] in ("created", "dry_run"):
            url = r.get("watch_url", "#")
            title = r.get("title", "—")
            start = (
                datetime.datetime.fromisoformat(r["start_time"]).strftime(
                    "%-I:%M %p PST"
                )
                if r.get("start_time")
                else "—"
            )
            thumb_icon = "🖼️ ✅" if r.get("thumbnail_uploaded") else "🖼️ ❌"
            event_rows += f"""
            <tr>
                <td style="padding:10px;border-bottom:1px solid #eee;font-weight:bold">{r['label']}</td>
                <td style="padding:10px;border-bottom:1px solid #eee">
                    <a href="{url}" style="color:#1a73e8;text-decoration:none">{title}</a>
                </td>
                <td style="padding:10px;border-bottom:1px solid #eee;text-align:center">{start}</td>
                <td style="padding:10px;border-bottom:1px solid #eee;text-align:center">{thumb_icon}</td>
                <td style="padding:10px;border-bottom:1px solid #eee;text-align:center">{icon}</td>
            </tr>"""
        else:
            event_rows += f"""
            <tr>
                <td style="padding:10px;border-bottom:1px solid #eee;font-weight:bold">{r['label']}</td>
                <td style="padding:10px;border-bottom:1px solid #eee;color:#888" colspan="3">{r.get('error','Unknown error')}</td>
                <td style="padding:10px;border-bottom:1px solid #eee;text-align:center">{icon}</td>
            </tr>"""

    summary_color = "#34a853" if all_ok else "#ea4335"
    summary_bg = "#e6f4ea" if all_ok else "#fce8e6"

    html = f"""
    <html><body style="font-family:Arial,sans-serif;max-width:700px;margin:auto;color:#333">

      <div style="background:#1a73e8;padding:24px;border-radius:8px 8px 0 0">
        <h1 style="color:white;margin:0;font-size:1.4em">YouTube Weekly Automation Report</h1>
        <p style="color:#cce0ff;margin:6px 0 0">Generated {run_date}</p>
      </div>

      <div style="background:{summary_bg};padding:14px 24px;border-left:4px solid {summary_color}">
        <strong style="color:{summary_color}">{status_line}</strong>
      </div>

      <!-- Viewer Report -->
      <div style="padding:24px 24px 0;background:#fff;border:1px solid #eee;border-bottom:none">
        <h2 style="margin:0 0 4px;font-size:1em;color:#555;text-transform:uppercase;letter-spacing:.05em">
          Last Sunday's Live Streams — {format_date(last_sunday)}
        </h2>
        <p style="margin:0 0 12px;font-size:.85em;color:#999">Peak concurrent viewers during the live broadcast</p>
        <table style="width:100%;border-collapse:collapse">
          <thead>
            <tr style="background:#f8f9fa">
              <th style="padding:10px;text-align:left;color:#666;font-size:.8em">CHANNEL</th>
              <th style="padding:10px;text-align:left;color:#666;font-size:.8em">STREAM</th>
              <th style="padding:10px;text-align:center;color:#666;font-size:.8em">PEAK VIEWERS</th>
              <th style="padding:10px;text-align:center;color:#666;font-size:.8em">STATUS</th>
            </tr>
          </thead>
          <tbody>{viewer_rows}</tbody>
        </table>
      </div>

      <!-- Event Creation -->
      <div style="padding:24px;background:#fff;border:1px solid #eee;margin-top:0">
        <h2 style="margin:0 0 4px;font-size:1em;color:#555;text-transform:uppercase;letter-spacing:.05em">
          Next Sunday's Events Created — {format_date(next_sunday)}
        </h2>
        <p style="margin:0 0 12px;font-size:.85em;color:#999">Live events automatically scheduled on YouTube</p>
        <table style="width:100%;border-collapse:collapse">
          <thead>
            <tr style="background:#f8f9fa">
              <th style="padding:10px;text-align:left;color:#666;font-size:.8em">CHANNEL</th>
              <th style="padding:10px;text-align:left;color:#666;font-size:.8em">EVENT TITLE</th>
              <th style="padding:10px;text-align:center;color:#666;font-size:.8em">START TIME</th>
              <th style="padding:10px;text-align:center;color:#666;font-size:.8em">THUMBNAIL</th>
              <th style="padding:10px;text-align:center;color:#666;font-size:.8em">STATUS</th>
            </tr>
          </thead>
          <tbody>{event_rows}</tbody>
        </table>
      </div>

      <div style="padding:14px 24px;background:#f8f9fa;border-radius:0 0 8px 8px;font-size:.8em;color:#999;border:1px solid #eee;border-top:none">
        Automated by YT Live Automation · Runs every Tuesday · sjcac.org
      </div>

    </body></html>
    """
    return subject, html


def send_email(subject: str, html_body: str) -> bool:
    """
    Send the weekly report email via Amazon SES.

    Uses SES_FROM_EMAIL, SES_TO_EMAIL, and SES_REGION from Lambda env vars.
    SES_FROM_EMAIL must be a verified sender identity in your AWS SES account.

    Returns True if the email was accepted by SES, False on failure.
    Email failures are logged but do not cause the Lambda to return an error —
    the YouTube tasks are unaffected regardless of email status.
    """
    ses = boto3.client("ses", region_name=os.environ.get("SES_REGION", "us-west-2"))
    try:
        ses.send_email(
            Source=os.environ["SES_FROM_EMAIL"],
            Destination={"ToAddresses": [os.environ["SES_TO_EMAIL"]]},
            Message={
                "Subject": {"Data": subject, "Charset": "UTF-8"},
                "Body": {"Html": {"Data": html_body, "Charset": "UTF-8"}},
            },
        )
        logger.info("Email sent to %s", os.environ["SES_TO_EMAIL"])
        return True
    except ClientError as e:
        logger.error("SES send failed: %s", e.response["Error"]["Message"])
        return False


# ══════════════════════════════════════════════════════════════════════════════
# SHEET SYNC — sends viewer counts to the Google Sheet's Raw Log
# ══════════════════════════════════════════════════════════════════════════════
# POSTs successful viewer counts to the Apps Script Web App, which logs them
# into the Raw Log tab via the same logAttendance() function the attendance
# form uses. Requires SHEET_WEBAPP_URL and SHEET_WEBAPP_SECRET env vars —
# the secret must match WEBAPP_SHARED_SECRET in lambda_integration.gs exactly.


def send_to_sheet(viewer_results: list, last_sunday: datetime.date) -> dict:
    """
    Sends successful viewer counts to the Sheet's Web App endpoint.

    Only sends channels where the viewer report actually succeeded — a
    failed/error channel just doesn't get sent, rather than sending a
    zero or null that could look like a real reported value.

    Non-fatal by design, same as send_email: a Sheet-side hiccup here
    should never block or fail the YouTube automation itself.
    """
    webapp_url = os.environ.get("SHEET_WEBAPP_URL")
    webapp_secret = os.environ.get("SHEET_WEBAPP_SECRET")

    if not webapp_url or not webapp_secret:
        logger.warning("SHEET_WEBAPP_URL or SHEET_WEBAPP_SECRET not configured — skipping sheet sync")
        return {"status": "skipped", "reason": "not configured"}

    results_to_send = []
    for r in viewer_results:
        if r.get("status") == "success" and r.get("max_concurrent_viewers") is not None:
            results_to_send.append({
                "channel": r["channel"],
                "date": str(last_sunday),
                "viewers": r["max_concurrent_viewers"],
            })

    if not results_to_send:
        logger.info("No successful viewer results to send to sheet")
        return {"status": "skipped", "reason": "no successful results"}

    payload = json.dumps({
        "secret": webapp_secret,
        "results": results_to_send,
    }).encode("utf-8")

    req = urllib.request.Request(
        webapp_url,
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST",
    )

    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            body = response.read().decode("utf-8")
            logger.info("Sheet sync response: %s", body)
            return {"status": "sent", "response": json.loads(body)}
    except urllib.error.URLError as e:
        logger.error("Sheet sync failed: %s", e)
        return {"status": "error", "error": str(e)}


# ══════════════════════════════════════════════════════════════════════════════
# LAMBDA HANDLER — entry point
# ══════════════════════════════════════════════════════════════════════════════


def lambda_handler(event: dict, context: Any) -> dict:
    """
    Lambda entry point. Invoked automatically every Tuesday via EventBridge.

    Iterates over all channels in CHANNELS, runs the viewer report and/or
    event creation tasks based on the mode, then sends a summary email.

    The event payload controls what runs:
        {}                              Run both tasks for all channels + send email.
        {"mode": "viewer_report"}       Only fetch viewer counts and send email.
        {"mode": "create_events"}       Only create next Sunday's events.
        {"channel": "ms_channel"}       Run both tasks for one channel only.
        {"dry_run": true}               Full run with no YouTube writes or email.

    Always returns HTTP 200 with a JSON body containing a summary and the
    per-channel results for both tasks. Errors on individual channels are
    captured in the results and do not cause a non-200 response.
    """
    mode = event.get("mode", "both")  # "both" | "viewer_report" | "create_events"
    target_channel = event.get("channel")  # optional single-channel filter
    dry_run = event.get("dry_run", False)

    last_sunday = get_last_sunday()
    next_sunday = get_next_sunday()

    logger.info(
        "Lambda invoked | mode=%s | channel=%s | dry_run=%s | last_sunday=%s | next_sunday=%s",
        mode,
        target_channel or "all",
        dry_run,
        last_sunday,
        next_sunday,
    )

    viewer_results = []
    event_results = []

    for channel_key, channel in CHANNELS.items():
        if target_channel and channel_key != target_channel:
            continue

        if mode in ("both", "viewer_report"):
            viewer_results.append(fetch_viewer_stats(channel_key, channel, last_sunday))

        if mode in ("both", "create_events") and channel.get("create_events", True):
            event_results.append(
                schedule_next_event(channel_key, channel, next_sunday, dry_run)
            )

    # Sync viewer counts to the Google Sheet's Raw Log (skip during dry_run)
    sheet_sync_result = None
    if mode in ("both", "viewer_report") and not dry_run:
        sheet_sync_result = send_to_sheet(viewer_results, last_sunday)

    # Send combined email (skip for single-channel runs or dry_run)
    email_sent = False
    if not target_channel and not dry_run and mode in ("both", "viewer_report"):
        subject, html_body = build_email(
            viewer_results, event_results, last_sunday, next_sunday
        )
        email_sent = send_email(subject, html_body)

    v_ok = sum(1 for r in viewer_results if r["status"] == "success")
    v_err = sum(1 for r in viewer_results if r["status"] == "error")
    e_ok = sum(1 for r in event_results if r["status"] in ("created", "dry_run"))
    e_err = sum(1 for r in event_results if r["status"] == "error")

    summary = {
        "last_sunday": str(last_sunday),
        "next_sunday": str(next_sunday),
        "email_sent": email_sent,
        "sheet_sync": sheet_sync_result,
        "viewer_report": {"success": v_ok, "errors": v_err},
        "event_creation": {"success": e_ok, "errors": e_err},
    }

    logger.info("Done: %s", summary)
    return {
        "statusCode": 200,
        "body": json.dumps(
            {
                "summary": summary,
                "viewer_results": viewer_results,
                "event_results": event_results,
            }
        ),
    }
